import dynamic from "next/dynamic";
import markdownIt from "@/utils/markdowIt";
import path from "path";
import { getMdFiles } from "@/utils";
import { get } from "@/utils/axios";

import Layout from "@/Layout";
import Head from "next/head";
import Markdown from "@/components/Markdown";
import AuthorCard from "@/components/Author";

const MarkdownMenu = dynamic(() => import("@/components/MarkdownMenu"), {
	ssr: false,
});

import type { NextApiRequest, NextApiResponse } from "next";
import type { AppProps } from "next/app";

import type { IBlog } from "@/utils/ts.d.ts";
interface Iprops extends AppProps {
	markdown: string;
	detail: IBlog;
}

import styles from "@/styles/index-page.module.scss";

const Blog = ({ detail, markdown }: Iprops) => {
	return (
		<>
			<Head>
				<title>{detail?.title || "Yan Code"}</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
				<style></style>
			</Head>
			<Layout detail={detail} title={detail?.title}>
				<div className={styles["index"]}>
					<Markdown markdown={markdown || ""} />
					<div>
						<div
							style={{
								marginBottom: "20px",
							}}
						>
							<AuthorCard />
						</div>
						<MarkdownMenu markdownContent={markdown || ""} />
					</div>
				</div>
			</Layout>
		</>
	);
};

export default Blog;

export const getContent = async (id: number) => {
	const data = await get("/api/mock/blog-default", {
		id,
	});
	return data;
};

export async function getServerSideProps(context: { params: any }) {
	const { params } = context;
	const { id } = params; // 获取动态路由参数

	const data = await getContent(id);

	return {
		props: {
			// @ts-ignore
			detail: data?.detail,
			// @ts-ignore
			markdown: markdownIt(data?.markdown),
		},
	};
}
