import markdownIt from "@/utils/markdowIt";

import Layout from "@/Layout";
import Head from "next/head";

import type { NextApiRequest, NextApiResponse } from "next";
import type { AppProps } from "next/app";
interface Iprops extends AppProps {
	markdown: string;
}

const Blog = (props: Iprops) => {
	console.log(props);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
				<style>
					{`
            :root {
              --blog-main: red !important;
            }
          `}
				</style>
			</Head>
			<Layout>
				<div
					style={{
						padding: "1rem 1.5rem",
					}}
				>
					<div
						dangerouslySetInnerHTML={{ __html: props?.markdown || "" }}
					></div>
					123
				</div>
			</Layout>
		</>
	);
};

export default Blog;

export async function getServerSideProps({
	req,
	res,
}: {
	req: NextApiRequest;
	res: NextApiResponse;
}) {
	// console.log(req, res, "控制台输出");
	// var result = MarkdownIt("::: spoiler click me\n*content*\n:::\n");
	var result = markdownIt(`# 我是标题`);
	// var result = MarkdownIt(`@ header
	// contentTwo
	// `);
	// console.log(result);

	res.setHeader(
		"Cache-Control",
		"public, s-maxage=10, stale-while-revalidate=59"
	);
	return {
		props: {
			headerMenus: [
				{
					lable: "测试",
					id: 1,
				},
			],
			markdown: result,
		}, // will be passed to the page component as props
	};
}
