import { get } from "@/utils/axios";

import Layout from "@/Layout";
import Head from "next/head";
import List from "@/components/List/One";
import Author from "@/components/Author";

import type { AppProps } from "next/app";

import type { IBlog } from "@/utils/ts.d.ts";
interface Iprops extends AppProps {
	list: IBlog[];
}

import classNames from "classnames";
import styles from "@/styles/blog-list-page.module.scss";

const BlogList = ({ list }: Iprops) => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
				<style>
					{/* {`
            :root {
              --blog-main: red !important;
            }
          `} */}
				</style>
			</Head>
			<Layout title='所有文章'>
				<div className={styles["blog-list-page"]}>
					<div className={classNames(styles["list"], "slide-box")}>
						<div className={styles["title"]}>
							文章
							<sup>{list?.length || 0}</sup>
						</div>
						<div className={styles["blog-content"]}>
							{list?.map((i: IBlog) => {
								return <List key={i?.id} detail={i} />;
							})}
						</div>
					</div>
					<div className='slide-box-content'>
						<Author />
					</div>
				</div>
			</Layout>
		</>
	);
};

export default BlogList;

export const getContent = async () => {
	const data = await get("/api/mock/blog");
	return data;
};

export const getStaticProps = async () => {
	return {
		props: {
			list: await getContent(),
		},
	};
};
