import markdownIt from "@/utils/markdowIt";
import path from "path";
import { getMdFiles } from "@/utils";

import Layout from "@/Layout";
import Head from "next/head";
import List from "@/components/List";
import Author from "@/components/Author";

import type { AppProps } from "next/app";

interface Iprops extends AppProps {
	markdown: string;
}

import classNames from "classnames";
import styles from "@/styles/blog-list-page.module.scss";

const BlogList = (props: Iprops) => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
				<style>
					{/* {`
            :root {
              --blog-main: red !important;
            }
          `} */}
				</style>
			</Head>
			<Layout title=''>
				<div className={styles["blog-list-page"]}>
					<div className={classNames(styles["list"], "slide-box")}>
						<div className={styles["title"]}>
							文章
							<sup>111</sup>
						</div>
						<div className={styles["blog-content"]}>
							<List.ListOne />
							<List.ListOne />
							<List.ListOne />
							<List.ListOne />
						</div>
					</div>
					<div className='slide-box-content'>
						<Author />
					</div>
				</div>
			</Layout>
		</>
	);
};

export default BlogList;
