import request from "@/utils/axios";

import Layout from "@/Layout";
import Head from "next/head";
import Tags from "@/components/BusComponents/Tags";

import type { NextApiRequest, NextApiResponse } from "next";
import type { AppProps } from "next/app";

import classNames from "classnames";
import styles from "@/styles/categories-page.module.scss";

interface ICategoriesPage extends AppProps {
	categories?: { id: number; name: string }[];
}

const CategoriesPage = ({ categories }: ICategoriesPage) => {
	return (
		<>
			<Head>
				<title>分类</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout title='分类'>
				<h1 className='slide-box'>分类</h1>
				<div
					className={classNames(
						styles["categories-content"],
						"slide-box-content"
					)}
				>
					{categories?.map((i: any) => {
						return <Tags key={i?.id} name={i?.name} num={i?.num || 0} />;
					})}
				</div>
			</Layout>
		</>
	);
};

export default CategoriesPage;

export const getContent = async () => {
	const data = await request({
		url: "/api/mock/categories",
		method: "GET",
	});
	return data;
};

// 不需要频繁请求
export const getStaticProps = async () => {
	return {
		props: {
			categories: await getContent(),
		},
	};
};
