import Layout from "@/Layout";
import Head from "next/head";
import { motion, animate } from "framer-motion";

import type { NextApiRequest, NextApiResponse } from "next";
import type { AppProps } from "next/app";

import classNames from "classnames";
import styles from "@/styles/demo/demo.module.scss";

interface Iprops extends AppProps {
	markdown?: string;
}

const DemoPage = () => {
	return (
		<>
			<Head>
				<title>测试页面</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Layout title='标签'>
				<h1>测试页面</h1>
				<div>
					{/* <motion.div
						className={styles["demo-box"]}
						// animate={{ x: 100, y: 100, scale: 0.5, rotate: "20deg" }}
						whileHover={{ scale: 1.2 }} // hover
						whileTap={{ scale: 1.1 }} // click
						drag='y'
						dragConstraints={{ left: -100, right: 100 }}
					/>
					<div
						className={styles["demo-box"]}
						onClick={() => animate(".boxes", { opacity: 0 })}
					></div> */}
					测试
					<div className={styles["hover-box"]}>
						<span>首页</span>
						<div className={classNames(styles["children"])}>
							<ul
								style={{
									display: "flex",
								}}
							>
								<li>测试</li>
								<li>测试1</li>
							</ul>
						</div>
					</div>
				</div>
			</Layout>
		</>
	);
};

export default DemoPage;

export async function getServerSideProps({
	req,
	res,
}: {
	req: NextApiRequest;
	res: NextApiResponse;
}) {
	return {
		props: {},
	};
}
